#!/bin/bash

#PBS -l select=1:ncpus=2:mem=10GB:arch=ivybridge
#PBS -l place=vscatter:shared
#PBS -l walltime=00:15:00

# no restart if job fails
#PBS -r n

#PBS -N canbus-ltl-5
#PBS -A ProB


MODEL=/home/phkoe102/models/CAN_BUS_tlc.mch

#OUTPUTDIR=/gpfs/project/$USER/$PBS_JOBID
ENDPOINT=/home/phkoe102/endpoint-$PBS_JOBID.probz
LTLFILE=/home/phkoe102/f-$PBS_JOBID.probz

#echo "P: Creating output dir"
#mkdir -p $OUTPUTDIR

echo "Requested amount of CPUs (per node): $OMP_NUM_THREADS"

PROB_HOME=/home/phkoe102/prob_ltsmin/ProB/
ZE_LD_PATH=/home/phkoe102/dest-install/lib/
PROB_LD_PATH=$ZE_LD_PATH:$PROB_HOME/lib

LTSMIN_SEQ=/home/phkoe102/dest-install/bin/prob2lts-seq
LTSMIN_SYM=/home/phkoe102/dest-install/bin/prob2lts-sym
LTSMIN_MC=/home/phkoe102/dest-install/bin/prob2lts-mc
PROBCLI=$PROB_HOME/probcli

touch $ENDPOINT
LD_LIBRARY_PATH=$PROB_LD_PATH $PROBCLI -ltsmin-ltl-output $LTLFILE -ltlformula "G (e(T1Wait) => X({T1_timer > 0}))" $MODEL
LD_LIBRARY_PATH=$PROB_LD_PATH $PROBCLI -ltsmin2 $ENDPOINT -ltlformula "G (e(T1Wait) => X({T1_timer > 0}))" $MODEL &
sleep 5
LD_LIBRARY_PATH=$ZE_LD_PATH /usr/bin/time -v $LTSMIN_SEQ -c $ENDPOINT --ltl=$LTLFILE --when
