#!/bin/bash

#PBS -l select=1:ncpus=2:mem=10GB:arch=ivybridge
#PBS -l place=vscatter:shared
#PBS -l walltime=02:00:00

# no restart if job fails
#PBS -r n

#PBS -N obsw-sym
#PBS -A ProB


MODEL=/home/phkoe102/models/obsw_M001.eventb

#OUTPUTDIR=/gpfs/project/$USER/$PBS_JOBID
ENDPOINT=/home/phkoe102/endpoint-$PBS_JOBID.probz

#echo "P: Creating output dir"
#mkdir -p $OUTPUTDIR

echo "Requested amount of CPUs (per node): $OMP_NUM_THREADS"

PROB_HOME=/home/phkoe102/prob_ltsmin/ProB/
ZE_LD_PATH=/home/phkoe102/dest-install/lib/
PROB_LD_PATH=$ZE_LD_PATH:$PROB_HOME/lib

LTSMIN_SEQ=/home/phkoe102/dest-install/bin/prob2lts-seq
LTSMIN_SYM=/home/phkoe102/dest-install/bin/prob2lts-sym
LTSMIN_MC=/home/phkoe102/dest-install/bin/prob2lts-mc
PROBCLI=$PROB_HOME/probcli

touch $ENDPOINT
LD_LIBRARY_PATH=$PROB_LD_PATH $PROBCLI -ltsmin2 $ENDPOINT $MODEL &
sleep 5
LD_LIBRARY_PATH=$ZE_LD_PATH /usr/bin/time -v $LTSMIN_SYM $ENDPOINT  --vset=lddmc -rbs,hf --order=chain --invariant='!is_init || (inv1 && inv2 && inv3 && inv4 && inv5 && inv6 && inv7 && inv8 && inv9)' --when
